In [2]:
import numpy as np

Problem 1: Create an integer identity matrix of size (5, 6). Print the Numpy array.

In [51]:
a = np.eye(5,6, k=0)

print("Matrix b : \n", a) 


Matrix b : 
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


Problem 2: Write a NumPy program to convert an array to a float type. Original array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]

In [11]:
A=np.array([1,2,3,4])

def int_float(A):
    for e in A:
        print(float(e))
        
int_float(A)

1.0
2.0
3.0
4.0


Problem 3 : Write a NumPy program to convert a list and tuple into arrays.

In [49]:
list_A=[1,2,3,4,5]
Tuple_A=(9,8,7,6,5)

def listTuple_array(A):
    for e in A: 
        print(np.array(e))

        
listTuple_array(Tuple_A)
print("*************")
listTuple_array(list_A)

9
8
7
6
5
*************
1
2
3
4
5


Problem 4 : Create an integer array of size 10, where all the values should be 0 but the fifth value should be 1.

In [24]:
(np.arange(10) == 4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

Problem 5 : What will be the output --> np.random.rand()

In [25]:
np.random.rand()

0.5527467137698244

Problem 6 : Given an integer array of size 10 and replace the first occurrence of maximum value by 0?

In [46]:

x = np.arange(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0 1 2 3 4 5 6 7 8 9]
Maximum value replaced by 0:
[0 1 2 3 4 5 6 7 8 0]


Problem 7 : Write a NumPy program to find the set difference of two arrays. 

In [41]:
array1 = np.array([0, 10, 20, 40, 60, 80])

array2 = [10, 30, 40, 50, 70]


def DiffOfTwoArray(A1,A2):
    print("Array1: ",A1)
    print("Array2: ",A2)
    print("Unique values in array1 that are not in array2:")
    diff=np.setdiff1d(A1, A2)
    return diff

DiffOfTwoArray(array1,array2)


Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values in array1 that are not in array2:


array([ 0, 20, 60, 80])

Problem 8 : Write a NumPy program to compute the determinant of a given square array.

In [36]:
import numpy 
matrix = np.array([[1,2],[3,4]])

def Det(matrix):
    det=np.linalg.det(matrix)
    return det

Det(matrix)

##((1*4) -(2*3))

-2.0000000000000004

Problem 9 : Write a NumPy program to compute the inverse of a given matrix

In [40]:
m = np.array([[1,2],[3,4]])


def Inverse_matrix(matrix):
    result=np.linalg.inv(matrix)
    print(f"Original matrix:{m}")
    return result

Inverse_matrix(m)

Original matrix:[[1 2]
 [3 4]]


array([[-2. ,  1. ],
       [ 1.5, -0.5]])